### ISSUE TITLE
Retargeting modifies target object

### ISSUE THREAD

**Issue by wolfg259** [upf-gti/retargeting-threejs#3]
When retargeting, the retargeted rotations seem correct but the target bone position or scale seems to be adjusted.
Retargeting is executed as:

```
    let options = {
              srcPoseMode: AnimationRetargeting.BindPoseModes.CURRENT, 
              trgPoseMode: AnimationRetargeting.BindPoseModes.CURRENT, 
              trgEmbedWorldTransforms: true,
              boneNameMap: {
                  'Hips': 'mixamorig1Hips',
                  'Spine': 'mixamorig1Spine',
                  'Spine1': 'mixamorig1Spine1',
                  'Spine2': 'mixamorig1Spine2',
                  'Neck': 'mixamorig1Neck',
                  'Head': 'mixamorig1Head',
                  'Shoulder_L': 'mixamorig1LeftShoulder',
                  'UpperArm_L': 'mixamorig1LeftArm',
                  'Forearm_L': 'mixamorig1LeftForeArm',
                  'Hand_L': 'mixamorig1LeftHand',
                  'Shoulder_R': 'mixamorig1RightShoulder',
                  'UpperArm_R': 'mixamorig1RightArm',
                  'Forearm_R': 'mixamorig1RightForeArm',
                  'Hand_R': 'mixamorig1RightHand',
                  'Thigh_L': 'mixamorig1LeftUpLeg',
                  'Shin_L': 'mixamorig1LeftLeg',
                  'Foot_L': 'mixamorig1LeftFoot',
                  'Toe_L': 'mixamorig1LeftToeBase',
                  'Thigh_R': 'mixamorig1RightUpLeg',
                  'Shin_R': 'mixamorig1RightLeg',
                  'Foot_R': 'mixamorig1RightFoot',
                  'Toe_R': 'mixamorig1RightToeBase'
              }
          }
          let retargeting = new AnimationRetargeting( source, fbxModel, options );
          const newClip = retargeting.retargetAnimation( sourceAnim );
```
Current target pose:
![image](https://github.com/user-attachments/assets/48c28203-1d40-4b32-b75a-7346873acbee)

Target armature after retargeting using an animation with only a single frame that is a t-pose for debugging (visualised skeletonHelper = current source pose):
![image](https://github.com/user-attachments/assets/f1318432-1bf0-4588-84f8-66590cb97472)

If having the original animation clip & target helps, feel free to contact me! wolf@anym.tech

**Comment by japopra** [comment]
The issue seemed to be a badly formatted BVH file. It included a position track for each joint, yet all values were set to 0 except for the hip joint, which contained meaningful values. This caused all bones to collapse onto the hips.

**Comment by wolfg259** [comment]
Hi, this is not the case; the BVH file is formatted without joint positions other than the hips, so [hip_pos, hip_rot, spine1_rot, ...]. Additionally, the BVH file visualises a motion as expected when loading it in Blender and also when visualising it using skeletonHelpers it works as expected in 3js. I solved this issue with this bvh file by changing the 7th line in `AnimationRetargeting.retargetAnimation()` to `if ( t.name.endsWith( ".position" ) && t.name.includes( Object.keys(this.boneMap.nameMap)[0]) ){ newTrack = this.retargetPositionTrack( t ); } ` such that retargetPositionTrack is only called for the hip bone, which fixed the issue for me. I had an email correspondence with your colleague Eva Valls-Garolera about this issue, perhaps you could ask her

**Comment by japopra** [comment]
Indeed, it was as you pointed out. The current state has that fixed already. Apologies for the misunderstanding.
